In [43]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
import pickle

In [44]:
data = pd.read_csv("Churn_Modelling.csv")

In [45]:
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [46]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 14 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   RowNumber        10000 non-null  int64
 1   CustomerId       10000 non-null  int64
 2   Surname          10000 non-null  object
 3   CreditScore      10000 non-null  int64
 4   Geography        10000 non-null  object
 5   Gender           10000 non-null  object
 6   Age              10000 non-null  int64
 7   Tenure           10000 non-null  int64
 8   Balance          10000 non-null  float64
 9   NumOfProducts    10000 non-null  int64
 10  HasCrCard        10000 non-null  int64
 11  IsActiveMember   10000 non-null  int64
 12  EstimatedSalary  10000 non-null  float64
 13  Exited           10000 non-null  int64
dtypes: float64(2), int64(9), object(3)
memory usage: 1.1+ MB

In [47]:
data = data.drop(["RowNumber", "CustomerId", "Surname"], axis=1)

In [48]:
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [49]:
label_encoder_gender = LabelEncoder()
data["Gender"] = label_encoder_gender.fit_transform(data["Gender"])
data.head()

,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,619,France,0,42,2,0.00,1,1,1,101348.88,1
1,608,Spain,0,41,1,83807.86,1,0,1,112542.58,0
2,502,France,0,42,8,159660.80,3,1,0,113931.57,1
3,699,France,0,39,1,0.00,2,0,0,93826.63,0
4,850,Spain,0,43,2,125510.82,1,1,1,79084.10,0

In [50]:
data["Geography"].unique()

array(['France', 'Spain', 'Germany'], dtype=object)

In [51]:
# label_encoder_geography = LabelEncoder()
# data["Geography"] = label_encoder_geography.fit_transform(data["Geography"])
# data.head()

In [52]:
import tensorflow as tf
from tensorflow.keras.models import Sequential

print("WORKING ✅")

WORKING ✅

In [53]:
from sklearn.preprocessing import OneHotEncoder
onehot_encoder_geo = OneHotEncoder()
geo_encoder = onehot_encoder_geo.fit_transform(data[["Geography"]])
geo_encoder.toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       ...,
       [1., 0., 0.],
       [0., 1., 0.],
       [1., 0., 0.]])

In [54]:
onehot_encoder_geo.get_feature_names_out(["Geography"])

array(['Geography_France', 'Geography_Germany', 'Geography_Spain'],
      dtype=object)

In [55]:
geo_encoder_df = pd.DataFrame(geo_encoder.toarray(), columns = onehot_encoder_geo.get_feature_names_out(["Geography"]))
geo_encoder_df.head()

   Geography_France  Geography_Germany  Geography_Spain
0               1.0                0.0              0.0
1               0.0                0.0              1.0
2               1.0                0.0              0.0
3               1.0                0.0              0.0
4               0.0                0.0              1.0

In [56]:
data = pd.concat([data.drop("Geography", axis=1), geo_encoder_df], axis=1)

In [57]:
data

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
9995,771,1,39,5,0.00,2,1,0,96270.64,0,1.0,0.0,0.0
9996,516,1,35,10,57369.61,1,1,1,101699.77,0,1.0,0.0,0.0
9997,709,0,36,7,0.00,1,0,1,42085.58,1,1.0,0.0,0.0
9998,772,1,42,3,75075.31,2,1,0,92888.52,1,0.0,1.0,0.0
9999,792,0,28,4,130142.79,1,1,0,38190.78,0,1.0,0.0,0.0

In [58]:
with open("label_encoder_gender.pkl", "wb") as file:
    pickle.dump(label_encoder_gender, file)

with open("onehot_encoder_geo.pkl", "wb") as file:
    pickle.dump(onehot_encoder_geo, file)

In [59]:
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [60]:
X = data.drop("Exited", axis=1)
y = data["Exited"]

In [61]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [62]:
X_test.shape, X_train.shape, y_test.shape, y_train.shape

((2000, 12), (8000, 12), (2000,), (8000,))

In [63]:
scaler = StandardScaler()

In [64]:
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [65]:
X_train

array([[ 0.35649971,  0.91324755, -0.6557859 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [-0.20389777,  0.91324755,  0.29493847, ..., -0.99850112,
         1.72572313, -0.57638802],
       [-0.96147213,  0.91324755, -1.41636539, ..., -0.99850112,
        -0.57946723,  1.73494238],
       ...,
       [ 0.86500853, -1.09499335, -0.08535128, ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.15932282,  0.91324755,  0.3900109 , ...,  1.00150113,
        -0.57946723, -0.57638802],
       [ 0.47065475,  0.91324755,  1.15059039, ..., -0.99850112,
         1.72572313, -0.57638802]])

In [66]:
with open("scaler.pkl", "wb") as file:
    pickle.dump(scaler, file)

In [67]:
!pip install tensorflow

Requirement already satisfied: tensorflow in .\tensornv\lib\site-packages (2.15.0)
Requirement already satisfied: tensorflow-intel==2.15.0 in .\tensornv\lib\site-packages (from tensorflow) (2.15.0)
Requirement already satisfied: absl-py>=1.0.0 in .\tensornv\lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (2.4.0)
Requirement already satisfied: astunparse>=1.6.0 in .\tensornv\lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (1.6.3)
Requirement already satisfied: flatbuffers>=23.5.26 in .\tensornv\lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (25.12.19)
Requirement already satisfied: gast!=0.5.0,!=0.5.1,!=0.5.2,>=0.2.1 in .\tensornv\lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (0.7.0)
Requirement already satisfied: google-pasta>=0.1.1 in .\tensornv\lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (0.2.0)
Requirement already satisfied: h5py>=2.9.0 in .\tensornv\lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (3.14.0)
Requirement already satisfied: libclang>=13.0.0 in .\tensornv\lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (18.1.1)
Requirement already satisfied: ml-dtypes~=0.2.0 in .\tensornv\lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (0.2.0)
Requirement already satisfied: numpy<2.0.0,>=1.23.5 in .\tensornv\lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (1.26.4)
Requirement already satisfied: opt-einsum>=2.3.2 in .\tensornv\lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (3.4.0)
Requirement already satisfied: packaging in .\tensornv\lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (26.0)
Requirement already satisfied: protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3 in .\tensornv\lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (4.25.8)
Requirement already satisfied: setuptools in .\tensornv\lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (65.5.0)
Requirement already satisfied: six>=1.12.0 in .\tensornv\lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (1.17.0)
Requirement already satisfied: termcolor>=1.1.0 in .\tensornv\lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (3.3.0)
Requirement already satisfied: typing-extensions>=3.6.6 in .\tensornv\lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (4.15.0)
Requirement already satisfied: wrapt<1.15,>=1.11.0 in .\tensornv\lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (1.14.2)
Requirement already satisfied: tensorflow-io-gcs-filesystem>=0.23.1 in .\tensornv\lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (0.31.0)
Requirement already satisfied: grpcio<2.0,>=1.24.3 in .\tensornv\lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (1.78.0)
Requirement already satisfied: tensorboard<2.16,>=2.15 in .\tensornv\lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (2.15.2)
Requirement already satisfied: tensorflow-estimator<2.16,>=2.15.0 in .\tensornv\lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (2.15.0)
Requirement already satisfied: keras<2.16,>=2.15.0 in .\tensornv\lib\site-packages (from tensorflow-intel==2.15.0->tensorflow) (2.15.0)
Requirement already satisfied: google-auth<3,>=1.6.3 in .\tensornv\lib\site-packages (from tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (2.49.1)
Requirement already satisfied: google-auth-oauthlib<2,>=0.5 in .\tensornv\lib\site-packages (from tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (1.3.0)
Requirement already satisfied: markdown>=2.6.8 in .\tensornv\lib\site-packages (from tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (3.10.2)
Requirement already satisfied: requests<3,>=2.21.0 in .\tensornv\lib\site-packages (from tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (2.32.5)
Requirement already satisfied: tensorboard-data-server<0.8.0,>=0.7.0 in .\tensornv\lib\site-packages (from tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (0.7.2)
Requirement already satisfied: werkzeug>=1.0.1 in .\tensornv\lib\site-packages (from tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (3.1.6)
Requirement already satisfied: pyasn1-modules>=0.2.1 in .\tensornv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (0.4.2)
Requirement already satisfied: cryptography>=38.0.3 in .\tensornv\lib\site-packages (from google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (46.0.5)
Requirement already satisfied: requests-oauthlib>=0.7.0 in .\tensornv\lib\site-packages (from google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (2.0.0)
Requirement already satisfied: charset_normalizer<4,>=2 in .\tensornv\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (3.4.6)
Requirement already satisfied: idna<4,>=2.5 in .\tensornv\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in .\tensornv\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in .\tensornv\lib\site-packages (from requests<3,>=2.21.0->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (2026.2.25)
Requirement already satisfied: wheel<1.0,>=0.23.0 in .\tensornv\lib\site-packages (from astunparse>=1.6.0->tensorflow-intel==2.15.0->tensorflow) (0.46.3)
Requirement already satisfied: cffi>=2.0.0 in .\tensornv\lib\site-packages (from cryptography>=38.0.3->google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (2.0.0)
Requirement already satisfied: pycparser in .\tensornv\lib\site-packages (from cffi>=2.0.0->cryptography>=38.0.3->google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (3.0)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in .\tensornv\lib\site-packages (from pyasn1-modules>=0.2.1->google-auth<3,>=1.6.3->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (0.6.3)
Requirement already satisfied: oauthlib>=3.0.0 in .\tensornv\lib\site-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib<2,>=0.5->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (3.3.1)
Requirement already satisfied: markupsafe>=2.1.1 in .\tensornv\lib\site-packages (from werkzeug>=1.0.1->tensorboard<2.16,>=2.15->tensorflow-intel==2.15.0->tensorflow) (3.0.3)

ANN Implementation

In [68]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.callbacks import EarlyStopping
import datetime

In [69]:
model = Sequential([
    Dense(64, activation="relu", input_shape=(X_train.shape[1],)),
    Dense(32, activation="relu"),
    Dense(1, activation="sigmoid")

])

In [70]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense_3 (Dense)             (None, 64)                832

 dense_4 (Dense)             (None, 32)                2080

 dense_5 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [71]:

import tensorflow



opt = tensorflow.keras.optimizers.Adam(learning_rate=0.01)
loss = tensorflow.keras.losses.BinaryCrossentropy()
loss

In [72]:
model.compile(optimizer="adam", loss="binary_crossentropy", metrics=["accuracy"])

In [73]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard

log_dir = "logs/fit20260317-163833/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(
    log_dir=log_dir,
    histogram_freq=1
)

In [74]:
early_stopping_callback = EarlyStopping(monitor="val_loss", patience=10, restore_best_weights=True)

In [75]:
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    batch_size=32,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
WARNING:tensorflow:From c:\Users\anike\OneDrive\Desktop\Krish Naik\DL\ANN Classification\tensornv\lib\site-packages\keras\src\utils\tf_utils.py:492: The name tf.ragged.RaggedTensorValue is deprecated. Please use tf.compat.v1.ragged.RaggedTensorValue instead.

WARNING:tensorflow:From c:\Users\anike\OneDrive\Desktop\Krish Naik\DL\ANN Classification\tensornv\lib\site-packages\keras\src\engine\base_layer_utils.py:384: The name tf.executing_eagerly_outside_functions is deprecated. Please use tf.compat.v1.executing_eagerly_outside_functions instead.

250/250 [==============================] - 2s 5ms/step - loss: 0.4671 - accuracy: 0.7878 - val_loss: 0.4050 - val_accuracy: 0.8215
Epoch 2/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3931 - accuracy: 0.8339 - val_loss: 0.3676 - val_accuracy: 0.8410
Epoch 3/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3589 - accuracy: 0.8566 - val_loss: 0.3552 - val_accuracy: 0.8465
Epoch 4/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3455 - accuracy: 0.8612 - val_loss: 0.3481 - val_accuracy: 0.8570
Epoch 5/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3393 - accuracy: 0.8620 - val_loss: 0.3477 - val_accuracy: 0.8555
Epoch 6/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3354 - accuracy: 0.8643 - val_loss: 0.3457 - val_accuracy: 0.8525
Epoch 7/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3329 - accuracy: 0.8627 - val_loss: 0.3448 - val_accuracy: 0.8540
Epoch 8/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3298 - accuracy: 0.8635 - val_loss: 0.3434 - val_accuracy: 0.8580
Epoch 9/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3279 - accuracy: 0.8664 - val_loss: 0.3421 - val_accuracy: 0.8565
Epoch 10/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3263 - accuracy: 0.8651 - val_loss: 0.3418 - val_accuracy: 0.8585
Epoch 11/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3228 - accuracy: 0.8662 - val_loss: 0.3436 - val_accuracy: 0.8560
Epoch 12/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3211 - accuracy: 0.8696 - val_loss: 0.3419 - val_accuracy: 0.8595
Epoch 13/100
250/250 [==============================] - 1s 3ms/step - loss: 0.3191 - accuracy: 0.8689 - val_loss: 0.3414 - val_accuracy: 0.8565
Epoch 14/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3177 - accuracy: 0.8705 - val_loss: 0.3366 - val_accuracy: 0.8620
Epoch 15/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3166 - accuracy: 0.8699 - val_loss: 0.3385 - val_accuracy: 0.8615
Epoch 16/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3144 - accuracy: 0.8702 - val_loss: 0.3443 - val_accuracy: 0.8585
Epoch 17/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3120 - accuracy: 0.8711 - val_loss: 0.3434 - val_accuracy: 0.8605
Epoch 18/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3120 - accuracy: 0.8696 - val_loss: 0.3426 - val_accuracy: 0.8620
Epoch 19/100
250/250 [==============================] - 1s 5ms/step - loss: 0.3108 - accuracy: 0.8714 - val_loss: 0.3405 - val_accuracy: 0.8570
Epoch 20/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3084 - accuracy: 0.8709 - val_loss: 0.3480 - val_accuracy: 0.8610
Epoch 21/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3081 - accuracy: 0.8717 - val_loss: 0.3528 - val_accuracy: 0.8575
Epoch 22/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3062 - accuracy: 0.8744 - val_loss: 0.3499 - val_accuracy: 0.8585
Epoch 23/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3055 - accuracy: 0.8750 - val_loss: 0.3457 - val_accuracy: 0.8550
Epoch 24/100
250/250 [==============================] - 1s 4ms/step - loss: 0.3041 - accuracy: 0.8749 - val_loss: 0.3427 - val_accuracy: 0.8590

In [76]:
model.save("model.h5")

c:\Users\anike\OneDrive\Desktop\Krish Naik\DL\ANN Classification\tensornv\lib\site-packages\keras\src\engine\training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(

In [77]:
%load_ext tensorboard

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard

In [78]:
!kill 11608

'kill' is not recognized as an internal or external command,
operable program or batch file.

In [79]:

tensorboard --logdir=logs/fit20260317-163833

Reusing TensorBoard on port 6006 (pid 24528), started 2:23:09 ago. (Use '!kill 24528' to kill it.)

In [25]:
import sys
print(sys.executable)

c:\Users\anike\OneDrive\Desktop\Krish Naik\DL\ANN Classification\tensornv\Scripts\python.exe